
- name: Ansible Ignore Errors - example 1
  template:
    src: ./index.html
    dest: /home/ubuntu/index.html
    register: copy_result
  ignore_errors: true

- name: Ansible Ignore Errors - example 2
  debug:
    msg: Hi {{ msg }}
  ignore_errors: true

- name: Check file is created or not
  command: touch /home/ubuntu/f2.txt
  register: file_check
  changed_when: file_check.rc == 0


