---
- name: "Create the file"
  hosts: all
  become: true
  roles:
    - python
    - handlers

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
          #   state: reloaded

