---
- name: Example Playbook for Environment Variables
  hosts: all
  become: true
    # remote_user: ubuntu
  roles:
    - custom-role
  
  environment:
    PLB_ENV: Playbook level env

  tasks:
    - name: Printing the playbook level env
      command: "echo $PLB_ENV"
  
    - name: Printing the Task level enviornment varable
      environment:
        MY_ENV: task level env
      ansible.builtin.command: "echo $MY_ENV"
        #  register: test

        #  - name: Check the env
        # debug:
        # var: test
        #
    - name: Check whether the task level env is accssible to other tasks
      command: "echo $MY_ENV --------------- $PLB_ENV"

